"use strict";
// The tour runs on the reviewed strong sample so every panel has content, then returns to the technician's own draft.
GuidedTour.create({triggerId:"tutorialDemo",finishLabel:"Finish walkthrough",
  onStart:()=>window.EscalationExample?.open(),
  onFinish:previous=>window.EscalationExample?.restore(previous),
  steps:[
  {target:".hero",title:"Welcome to the strong example",what:"The tour loaded the Strong Example — an iDRAC web interface returning HTTP 503 on one PowerEdge R750 — and reviewed it, so every panel has content. Your own draft is set aside and comes back when the tour ends. The status under the heading shows whether your draft is saved in this browser.",why:"You can see what a complete, ready escalation looks like before you fill in your own."},
  {target:"#caseTitle",container:".panel",title:"Identify the case at a glance",what:"Case Title is built automatically from System/Platform, OS/Solution, and the Problem statement. It updates as you type and appears first in the copied escalation.",why:"The receiving engineer recognizes the environment and the symptom before reading any further."},
  {target:"#sourceNotePanel",title:"Start from Case Notes",what:"Escalate to DE in Case Notes opens this page with matching fields filled in and the original note shown here. Exact errors, whether the issue is reproducible, the time zone, and results are not carried over, so answer those yourself.",why:"You don't retype what is already documented, and nothing is assumed on your behalf."},
  {target:"#problem",container:".panel",title:"Describe the issue and its impact",what:"Every field in this section is required: Problem statement, Severity, Service Impact, Affected Systems / Users, Business impact, Timeline and frequency, Customer Country, and the time zone the customer wants to work in.",why:"Severity, scope, and business impact let DE prioritize; the country and working time zone tell them when they can reach the customer."},
  {target:"#platform",container:".panel",title:"Provide technical context",what:"OS Support Entitlement Verification, OS version / build, OS/Solution, and Exact errors and timestamps are required. System/Platform is optional but feeds the Case Title. If no error is shown, say so — that counts as an answer.",why:"Exact versions and error text let the recipient search known issues and logs immediately."},
  {target:"#reproducible",container:".field",title:"Is this issue reproducible?",what:"Choose Yes or No; an answer is required. Yes reveals Reproduction steps, which are then required — use at least two numbered steps. For No, a detailed timeline of when and how often it happens earns the reproducibility credit instead.",why:"Steps DE can follow, or a precise timeline when the issue can't be triggered, save a round of clarification."},
  {target:"#troubleshooting",container:".panel",title:"Show the investigation",what:"Troubleshooting performed lists what you tried; Results and observations records what happened for each. Both are required, and results that simply repeat the troubleshooting text block readiness.",why:"Outcomes show what has been ruled out, so DE doesn't repeat completed work."},
  {target:"#evidence",container:".log-helper-location",title:"Confirm the required logs",what:"Choose Yes or No; an answer is required. Yes requires a Log Location — a case attachment, share path, or link. No requires the Reason logs cannot be obtained.",why:"DE can open the evidence right away, or knows up front why it is missing."},
  {target:"#openLogHelper",title:"Plan the right log collection",what:"Which logs should I collect? opens the same collection guidance as Case Notes for the selected OS and issue, with commands to copy and links to guides. A plan brought over from Case Notes appears as Planned log collection; it does not count as logs gathered.",why:"Ask the customer for the right logs the first time, and keep planned collection separate from evidence you already have."},
  {target:"#changes",container:".field",title:"Record recent changes",what:"Recent changes is required. List updates, configuration changes, or deployments before the issue began. “None” is accepted when nothing changed; “Unknown” is not.",why:"A recent change is often the fastest lead to the cause."},
  {target:"#addAction",container:".panel",title:"Pair each action with its outcome",what:"Add action and result keeps each troubleshooting step beside its observed outcome. The rows are added to the investigation fields when you review and copy.",why:"Clear action/result pairs earn full troubleshooting credit and are easy for DE to scan."},
  {target:"#escalationForm .form-actions",title:"Review the escalation",what:"Review escalation scores the form and checks every required field. Clear removes the form and its saved draft after you confirm. Any edit after a review requires a fresh review before you can copy.",why:"Gaps are caught here instead of in a request for information from DE."},
  {target:"#scoreRing",container:".score-header",title:"Read the result",what:"The result shows the status and a score out of 100. Ready needs 75 or more and no blocking issues. The strong example is Ready.",why:"One glance tells you whether the escalation can go."},
  {target:"#categoryGrid",title:"See where points come from",what:"The score is split into Completeness (35), Specificity (20), Reproducibility (15), Evidence (15), and Troubleshooting (15). How readiness is scored, below the results, explains each rule.",why:"You can see exactly which area needs more detail rather than guessing."},
  {target:"#strengthsSection",title:"Use the feedback",what:"The strong example has no gaps, so only What's working is listed. When something is missing, Blocking issues (must be fixed before it is ready) and Recommendations (raise the score) appear above it. Each item names its field, and the same feedback appears under that field in the form.",why:"Feedback points you straight to the field to fix."},
  {target:"#copySection",title:"Copy the handoff",what:"The preview shows the exact text that Copy escalation data puts on your clipboard, starting with the Case Title. Copy works only after a fresh review of the current details.",why:"You control the final text, and what you paste always matches what was reviewed."},
  {target:".devin-copy",title:"Get help from AI",what:"Ask AI to chooses a task. Copy to AI copies a prompt with the escalation data for your AI tool; Send to Devin sends it once Devin is connected in AI Settings. Add your Own AI Prompt/skills saves your own tasks.",why:"AI can spot gaps or tighten wording. Review its suggestions before applying them."},
  {target:"#trainingMenu",title:"Practice with examples",what:"The Training menu reopens this tutorial and loads the Weak or Strong Example into the form. Loading an example asks before replacing your draft.",why:"Comparing the weak and strong examples shows what reviewers look for."},
  {target:"#toolsMenu",title:"Open related tools",what:"Tools links to the Tools Hub, Troubleshooting Guides, the ISG Tools Catalog, and Microsoft Support Tools.",why:"Reference material is one click away while you document the case."},
  {target:"#settingsMenu",title:"Site settings",what:"Settings opens Customize Fields and Backup & Restore, which live in Case Notes.",why:"Field layout and backups are managed in one place for the whole site."},
  {target:"#requestFeature",title:"Request a feature or report a bug",what:"Opens a pre-filled request for this page. Describe what you need without customer names, Service Tags, SR numbers, or logs.",why:"Your feedback shapes the next improvements."},
  {target:"#themeToggle",title:"Switch light or dark mode",what:"Toggles the theme for every page on this site; your choice is remembered in this browser. When you finish, the tour restores your own draft.",why:"Work comfortably in whatever lighting you're in."}
]});
