"use strict";
GuidedTour.create({triggerId:"showDemo",finishLabel:"Finish walkthrough",steps:[
  {target:"#caseTitle",container:".panel",title:"Identify the case at a glance",what:"Case Title combines Server Type/System Platform, OS, and Issue Description. It updates from the source fields and appears first in the copied escalation.",why:"The receiving engineer can quickly recognize the affected environment and symptom."},
  {target:"#problem",container:".panel",title:"Explain the issue and impact",what:"Describe what fails, who is affected, when it happens, and what should happen. Record severity and service impact.",why:"The next engineer needs both a precise technical problem and the customer impact to prioritize the handoff."},
  {target:"#platform",container:".panel",title:"Provide technical context",what:"Record platform, OS/build, support details, exact errors, and reproduction steps. Case Notes pre-fills matching fields when you use Escalate to DE.",why:"This gives the recipient a starting point and reduces clarification requests about the environment."},
  {target:"#troubleshooting",container:".panel",title:"Show the investigation",what:"Document actions taken, their observed results, available logs, and recent changes. If logs cannot be obtained, explain the constraint.",why:"Evidence and outcomes help the recipient decide what to test next without repeating completed work."},
  {target:"#openLogHelper",container:".log-helper-location",title:"Plan the right log collection",what:"Which logs should I collect? opens the same collection guidance as Case Notes for the current OS and issue type, with commands to copy and links to collection guides. Opening it does not mark logs as collected.",why:"Use it when you are unsure which artifacts will help. It distinguishes planned collection from evidence already available."},
  {target:"#addAction",container:".panel",title:"Pair each action with its outcome",what:"Use Add action and result to keep a troubleshooting step beside the observed outcome. These rows also contribute to the investigation fields.",why:"A clear action/result pair shows what was ruled out and where the failure remains."},
  {target:"#escalationForm .form-actions",title:"Review escalation readiness",what:"Review escalation checks completeness and evidence. A score of at least 75 with no blockers is ready; editing the case requires a fresh review.",why:"Review catches missing essentials before a handoff creates another request for information. The tour does not submit a review."},
  {target:"#resultsPanel",title:"Use the feedback and copy the handoff",what:"After review, this section shows the score, blockers, recommendations, and copy preview. Follow feedback to the relevant field, then review again and copy the ready escalation.",why:"Make the handoff actionable while keeping control over the final text. The demo leaves your draft and review status unchanged."}
]});
